export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

import "@/styles/dashboard_globals.css"

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className="dark">
      <body className="bg-background text-foreground">
        {children}
      </body>
    </html>
  )
}
